// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/clamav/v1/scanner.proto

package clamavv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerdictStatus int32

const (
	VerdictStatus_VERDICT_UNSPECIFIED VerdictStatus = 0
	VerdictStatus_CLEAN               VerdictStatus = 1
	VerdictStatus_INFECTED            VerdictStatus = 2
)

// Enum value maps for VerdictStatus.
var (
	VerdictStatus_name = map[int32]string{
		0: "VERDICT_UNSPECIFIED",
		1: "CLEAN",
		2: "INFECTED",
	}
	VerdictStatus_value = map[string]int32{
		"VERDICT_UNSPECIFIED": 0,
		"CLEAN":               1,
		"INFECTED":            2,
	}
)

func (x VerdictStatus) Enum() *VerdictStatus {
	p := new(VerdictStatus)
	*p = x
	return p
}

func (x VerdictStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VerdictStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_clamav_v1_scanner_proto_enumTypes[0].Descriptor()
}

func (VerdictStatus) Type() protoreflect.EnumType {
	return &file_proto_clamav_v1_scanner_proto_enumTypes[0]
}

func (x VerdictStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VerdictStatus.Descriptor instead.
func (VerdictStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_clamav_v1_scanner_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_clamav_v1_scanner_proto_enumTypes[1].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_proto_clamav_v1_scanner_proto_enumTypes[1]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_clamav_v1_scanner_proto_rawDescGZIP(), []int{6, 0}
}

type FileMetadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FileName       string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ConsumerName   string                 `protobuf:"bytes,2,opt,name=consumer_name,json=consumerName,proto3" json:"consumer_name,omitempty"`
	ExpectedSha256 string                 `protobuf:"bytes,3,opt,name=expected_sha256,json=expectedSha256,proto3" json:"expected_sha256,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_proto_clamav_v1_scanner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clamav_v1_scanner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_proto_clamav_v1_scanner_proto_rawDescGZIP(), []int{0}
}

func (x *FileMetadata) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileMetadata) GetConsumerName() string {
	if x != nil {
		return x.ConsumerName
	}
	return ""
}

func (x *FileMetadata) GetExpectedSha256() string {
	if x != nil {
		return x.ExpectedSha256
	}
	return ""
}

type ScanChunkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ScanChunkRequest_Metadata
	//	*ScanChunkRequest_ChunkData
	Payload       isScanChunkRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanChunkRequest) Reset() {
	*x = ScanChunkRequest{}
	mi := &file_proto_clamav_v1_scanner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanChunkRequest) ProtoMessage() {}

func (x *ScanChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clamav_v1_scanner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanChunkRequest.ProtoReflect.Descriptor instead.
func (*ScanChunkRequest) Descriptor() ([]byte, []int) {
	return file_proto_clamav_v1_scanner_proto_rawDescGZIP(), []int{1}
}

func (x *ScanChunkRequest) GetPayload() isScanChunkRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ScanChunkRequest) GetMetadata() *FileMetadata {
	if x != nil {
		if x, ok := x.Payload.(*ScanChunkRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *ScanChunkRequest) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ScanChunkRequest_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

type isScanChunkRequest_Payload interface {
	isScanChunkRequest_Payload()
}

type ScanChunkRequest_Metadata struct {
	Metadata *FileMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type ScanChunkRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*ScanChunkRequest_Metadata) isScanChunkRequest_Payload() {}

func (*ScanChunkRequest_ChunkData) isScanChunkRequest_Payload() {}

type ThreatInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VirusName     string                 `protobuf:"bytes,1,opt,name=virus_name,json=virusName,proto3" json:"virus_name,omitempty"`
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	ActionTaken   string                 `protobuf:"bytes,3,opt,name=action_taken,json=actionTaken,proto3" json:"action_taken,omitempty"`
	QuarantineId  string                 `protobuf:"bytes,4,opt,name=quarantine_id,json=quarantineId,proto3" json:"quarantine_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreatInfo) Reset() {
	*x = ThreatInfo{}
	mi := &file_proto_clamav_v1_scanner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreatInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreatInfo) ProtoMessage() {}

func (x *ThreatInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clamav_v1_scanner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreatInfo.ProtoReflect.Descriptor instead.
func (*ThreatInfo) Descriptor() ([]byte, []int) {
	return file_proto_clamav_v1_scanner_proto_rawDescGZIP(), []int{2}
}

func (x *ThreatInfo) GetVirusName() string {
	if x != nil {
		return x.VirusName
	}
	return ""
}

func (x *ThreatInfo) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *ThreatInfo) GetActionTaken() string {
	if x != nil {
		return x.ActionTaken
	}
	return ""
}

func (x *ThreatInfo) GetQuarantineId() string {
	if x != nil {
		return x.QuarantineId
	}
	return ""
}

type ScanData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FileName       string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize       int64                  `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	FileSha256     string                 `protobuf:"bytes,3,opt,name=file_sha256,json=fileSha256,proto3" json:"file_sha256,omitempty"`
	ScanDurationMs int64                  `protobuf:"varint,4,opt,name=scan_duration_ms,json=scanDurationMs,proto3" json:"scan_duration_ms,omitempty"`
	ScannedAt      string                 `protobuf:"bytes,5,opt,name=scanned_at,json=scannedAt,proto3" json:"scanned_at,omitempty"`
	Whitelisted    bool                   `protobuf:"varint,6,opt,name=whitelisted,proto3" json:"whitelisted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScanData) Reset() {
	*x = ScanData{}
	mi := &file_proto_clamav_v1_scanner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanData) ProtoMessage() {}

func (x *ScanData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clamav_v1_scanner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanData.ProtoReflect.Descriptor instead.
func (*ScanData) Descriptor() ([]byte, []int) {
	return file_proto_clamav_v1_scanner_proto_rawDescGZIP(), []int{3}
}

func (x *ScanData) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ScanData) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *ScanData) GetFileSha256() string {
	if x != nil {
		return x.FileSha256
	}
	return ""
}

func (x *ScanData) GetScanDurationMs() int64 {
	if x != nil {
		return x.ScanDurationMs
	}
	return 0
}

func (x *ScanData) GetScannedAt() string {
	if x != nil {
		return x.ScannedAt
	}
	return ""
}

func (x *ScanData) GetWhitelisted() bool {
	if x != nil {
		return x.Whitelisted
	}
	return false
}

type ScanVerdictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Verdict       VerdictStatus          `protobuf:"varint,2,opt,name=verdict,proto3,enum=clamav.v1.VerdictStatus" json:"verdict,omitempty"`
	Threat        *ThreatInfo            `protobuf:"bytes,3,opt,name=threat,proto3" json:"threat,omitempty"`
	Data          *ScanData              `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanVerdictResponse) Reset() {
	*x = ScanVerdictResponse{}
	mi := &file_proto_clamav_v1_scanner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanVerdictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanVerdictResponse) ProtoMessage() {}

func (x *ScanVerdictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clamav_v1_scanner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanVerdictResponse.ProtoReflect.Descriptor instead.
func (*ScanVerdictResponse) Descriptor() ([]byte, []int) {
	return file_proto_clamav_v1_scanner_proto_rawDescGZIP(), []int{4}
}

func (x *ScanVerdictResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ScanVerdictResponse) GetVerdict() VerdictStatus {
	if x != nil {
		return x.Verdict
	}
	return VerdictStatus_VERDICT_UNSPECIFIED
}

func (x *ScanVerdictResponse) GetThreat() *ThreatInfo {
	if x != nil {
		return x.Threat
	}
	return nil
}

func (x *ScanVerdictResponse) GetData() *ScanData {
	if x != nil {
		return x.Data
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_clamav_v1_scanner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clamav_v1_scanner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_clamav_v1_scanner_proto_rawDescGZIP(), []int{5}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=clamav.v1.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	Version       string                            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Engine        string                            `protobuf:"bytes,3,opt,name=engine,proto3" json:"engine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_clamav_v1_scanner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clamav_v1_scanner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_clamav_v1_scanner_proto_rawDescGZIP(), []int{6}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

var File_proto_clamav_v1_scanner_proto protoreflect.FileDescriptor

const file_proto_clamav_v1_scanner_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/clamav/v1/scanner.proto\x12\tclamav.v1\"y\n" +
	"\fFileMetadata\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12#\n" +
	"\rconsumer_name\x18\x02 \x01(\tR\fconsumerName\x12'\n" +
	"\x0fexpected_sha256\x18\x03 \x01(\tR\x0eexpectedSha256\"u\n" +
	"\x10ScanChunkRequest\x125\n" +
	"\bmetadata\x18\x01 \x01(\v2\x17.clamav.v1.FileMetadataH\x00R\bmetadata\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkDataB\t\n" +
	"\apayload\"\x8f\x01\n" +
	"\n" +
	"ThreatInfo\x12\x1d\n" +
	"\n" +
	"virus_name\x18\x01 \x01(\tR\tvirusName\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12!\n" +
	"\faction_taken\x18\x03 \x01(\tR\vactionTaken\x12#\n" +
	"\rquarantine_id\x18\x04 \x01(\tR\fquarantineId\"\xd0\x01\n" +
	"\bScanData\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_size\x18\x02 \x01(\x03R\bfileSize\x12\x1f\n" +
	"\vfile_sha256\x18\x03 \x01(\tR\n" +
	"fileSha256\x12(\n" +
	"\x10scan_duration_ms\x18\x04 \x01(\x03R\x0escanDurationMs\x12\x1d\n" +
	"\n" +
	"scanned_at\x18\x05 \x01(\tR\tscannedAt\x12 \n" +
	"\vwhitelisted\x18\x06 \x01(\bR\vwhitelisted\"\xbb\x01\n" +
	"\x13ScanVerdictResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x122\n" +
	"\averdict\x18\x02 \x01(\x0e2\x18.clamav.v1.VerdictStatusR\averdict\x12-\n" +
	"\x06threat\x18\x03 \x01(\v2\x15.clamav.v1.ThreatInfoR\x06threat\x12'\n" +
	"\x04data\x18\x04 \x01(\v2\x13.clamav.v1.ScanDataR\x04data\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xc9\x01\n" +
	"\x13HealthCheckResponse\x12D\n" +
	"\x06status\x18\x01 \x01(\x0e2,.clamav.v1.HealthCheckResponse.ServingStatusR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06engine\x18\x03 \x01(\tR\x06engine\":\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02*A\n" +
	"\rVerdictStatus\x12\x17\n" +
	"\x13VERDICT_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05CLEAN\x10\x01\x12\f\n" +
	"\bINFECTED\x10\x022\xab\x01\n" +
	"\x0eScannerService\x12K\n" +
	"\n" +
	"ScanStream\x12\x1b.clamav.v1.ScanChunkRequest\x1a\x1e.clamav.v1.ScanVerdictResponse(\x01\x12L\n" +
	"\vHealthCheck\x12\x1d.clamav.v1.HealthCheckRequest\x1a\x1e.clamav.v1.HealthCheckResponseB=Z;github.com/vfat/vqf-clamav-service/proto/clamav/v1;clamavv1b\x06proto3"

var (
	file_proto_clamav_v1_scanner_proto_rawDescOnce sync.Once
	file_proto_clamav_v1_scanner_proto_rawDescData []byte
)

func file_proto_clamav_v1_scanner_proto_rawDescGZIP() []byte {
	file_proto_clamav_v1_scanner_proto_rawDescOnce.Do(func() {
		file_proto_clamav_v1_scanner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_clamav_v1_scanner_proto_rawDesc), len(file_proto_clamav_v1_scanner_proto_rawDesc)))
	})
	return file_proto_clamav_v1_scanner_proto_rawDescData
}

var file_proto_clamav_v1_scanner_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_clamav_v1_scanner_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_clamav_v1_scanner_proto_goTypes = []any{
	(VerdictStatus)(0),                     // 0: clamav.v1.VerdictStatus
	(HealthCheckResponse_ServingStatus)(0), // 1: clamav.v1.HealthCheckResponse.ServingStatus
	(*FileMetadata)(nil),                   // 2: clamav.v1.FileMetadata
	(*ScanChunkRequest)(nil),               // 3: clamav.v1.ScanChunkRequest
	(*ThreatInfo)(nil),                     // 4: clamav.v1.ThreatInfo
	(*ScanData)(nil),                       // 5: clamav.v1.ScanData
	(*ScanVerdictResponse)(nil),            // 6: clamav.v1.ScanVerdictResponse
	(*HealthCheckRequest)(nil),             // 7: clamav.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 8: clamav.v1.HealthCheckResponse
}
var file_proto_clamav_v1_scanner_proto_depIdxs = []int32{
	2, // 0: clamav.v1.ScanChunkRequest.metadata:type_name -> clamav.v1.FileMetadata
	0, // 1: clamav.v1.ScanVerdictResponse.verdict:type_name -> clamav.v1.VerdictStatus
	4, // 2: clamav.v1.ScanVerdictResponse.threat:type_name -> clamav.v1.ThreatInfo
	5, // 3: clamav.v1.ScanVerdictResponse.data:type_name -> clamav.v1.ScanData
	1, // 4: clamav.v1.HealthCheckResponse.status:type_name -> clamav.v1.HealthCheckResponse.ServingStatus
	3, // 5: clamav.v1.ScannerService.ScanStream:input_type -> clamav.v1.ScanChunkRequest
	7, // 6: clamav.v1.ScannerService.HealthCheck:input_type -> clamav.v1.HealthCheckRequest
	6, // 7: clamav.v1.ScannerService.ScanStream:output_type -> clamav.v1.ScanVerdictResponse
	8, // 8: clamav.v1.ScannerService.HealthCheck:output_type -> clamav.v1.HealthCheckResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_clamav_v1_scanner_proto_init() }
func file_proto_clamav_v1_scanner_proto_init() {
	if File_proto_clamav_v1_scanner_proto != nil {
		return
	}
	file_proto_clamav_v1_scanner_proto_msgTypes[1].OneofWrappers = []any{
		(*ScanChunkRequest_Metadata)(nil),
		(*ScanChunkRequest_ChunkData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_clamav_v1_scanner_proto_rawDesc), len(file_proto_clamav_v1_scanner_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_clamav_v1_scanner_proto_goTypes,
		DependencyIndexes: file_proto_clamav_v1_scanner_proto_depIdxs,
		EnumInfos:         file_proto_clamav_v1_scanner_proto_enumTypes,
		MessageInfos:      file_proto_clamav_v1_scanner_proto_msgTypes,
	}.Build()
	File_proto_clamav_v1_scanner_proto = out.File
	file_proto_clamav_v1_scanner_proto_goTypes = nil
	file_proto_clamav_v1_scanner_proto_depIdxs = nil
}
